name: Run_Google_Indexing
on: workflow_dispatch
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Start
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          GOOGLE_CREDENTIALS_JSON: service_account.json
          SITEMAP_URL: https://liidl.shop
        run: |
          echo "$GOOGLE_JSON" > service_account.json
          python main.py
